[package]
name = "rust_api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.11.0"
chrono = "0.4.41"
futures-util = "0.3.31"
mongodb = "3.2.3"
serde = "1.0.219"

[dev-dependencies]
serde_json = "1.0"